version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3333:3000"
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/app:/usr/src/app
